export const fakeUsers = [
  { name: "Siti", xp: 424, isCurrentUser: false },
  { name: "Bobi", xp: 378, isCurrentUser: false },
  { name: "Cathy", xp: 249, isCurrentUser: false },
  { name: "Darren", xp: 216, isCurrentUser: false },
  { name: "Ela", xp: 211, isCurrentUser: false },
  { name: "Freddy", xp: 177, isCurrentUser: false },
  { name: "Garit", xp: 152, isCurrentUser: false },
  { name: "Helen", xp: 87, isCurrentUser: false },
  { name: "Isa", xp: 82, isCurrentUser: false },
  { name: "Laura", xp: 77, isCurrentUser: false },
  { name: "Kevin", xp: 72, isCurrentUser: false },
  { name: "Lukman", xp: 71, isCurrentUser: false },
  { name: "Marie", xp: 65, isCurrentUser: false },
  { name: "Nana", xp: 62, isCurrentUser: false },
  { name: "Onana", xp: 48, isCurrentUser: false },
  { name: "Putri", xp: 52, isCurrentUser: false },
  { name: "Luthfi", xp: 51, isCurrentUser: false },
  { name: "Rian", xp: 45, isCurrentUser: false },
  { name: "Stephen", xp: 40, isCurrentUser: false },
  { name: "Tono", xp: 30, isCurrentUser: false },
  { name: "Umi", xp: 20, isCurrentUser: false },
  { name: "Vincent R", xp: 10, isCurrentUser: false },
  { name: "Anisa", xp: 10, isCurrentUser: false },
  { name: "Andi", xp: 10, isCurrentUser: false },
  { name: "Alif", xp: 10, isCurrentUser: false },
  { name: "Didan", xp: 10, isCurrentUser: false },
  { name: "Nia", xp: 10, isCurrentUser: false },
  { name: "Jamal", xp: 10, isCurrentUser: false },
  { name: "Asep", xp: 10, isCurrentUser: false },
] as const;
